version: '3'

services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile
#    volumes:
#      - ./src:/app/my-app/src:z
#      - ./build:/app/my-app/build:z
    ports:
      - "3000:3000"
